export const TETRIS_HORIZONTAL_BLOCKS = 10;
export const TETRIS_VERTICAL_BLOCKS = 20;
export const BLOCK_SIZE = 32;
export const CANVAS_WIDTH = TETRIS_HORIZONTAL_BLOCKS * BLOCK_SIZE;
export const CANVAS_HEIGHT = TETRIS_VERTICAL_BLOCKS * BLOCK_SIZE;
